### PR TITLE
Merge whitelist into devel

### PR DESCRIPTION
**Pull request by Mcat12**
I think the whitelist is done for now. There are conflicts between the branches; probably because I moved the header and footer into different files.

### CODE REVIEW

**Comment by dschaper** [comment]
@Mcat12 Can you check the merge conflict resolution and see if it looks good to you?

**Comment by Mcat12** [comment]
I think it looks good... Were the only conflicts in the readme and api.php?

**Comment by dschaper** [comment]
No, just index.html. The rest merged okay.

**Comment by Mcat12** [comment]
Do you mean index.php? I only see the readme and api.php changed in the commit

**Comment by dschaper** [comment]
Sorry, yes I meant index.php. It's in the parent commits. If you pull the whitelist branch it should be set now to what will be merged into devel.

**Comment by Mcat12** [comment]
It's so annoying to not be able to see a commit graph since the AdminLTE fork list is too big for github... I'm going to see if I can find an easier way to figure this out.

**Comment by dschaper** [comment]
CLI

**Comment by Mcat12** [comment]
Ya. I kind of like [Github's](https://github.com/jacobsalmela/pi-hole/network) a little better though.

**Comment by dschaper** [comment]
Yeah, I guess that would look kind of nasty as a git log prettyprint in ascii

**Comment by Mcat12** [comment]
This looks interesting: http://ghv.artzub.com/

**Comment by Mcat12** [comment]
You can probably merge this.

**Pull request merged**
