### PR TITLE
Added frequent queries table

### PR DESCRIPTION
**Pull request by Horkyze**
I created table consisting of frequent queries. Data are taken from pihole.log as other statistics. Table toggles when user clicks "More info" in the DNS Queries Today box. This is how it looks: 
screen shot 2016-01-18 at 15 20 22

### CODE REVIEW

**Comment by jacobsalmela** [comment]
Nice, this looks beautiful.

Take a look at #15 though, as it will break some of your code, so you may want to look at working that out with @PromoFaux

**Comment by Mcat12** [comment]
Actually, I think his code will be fine. #15 changes lines 1-5 in index.php, while this adds a line after line 5 in index.php, plus some others.

**Comment by Horkyze** [comment]
#15 changes 1-7 as I can see. Anyway this can wait till #15 is merged, then I can resolve created conflicts.

**Comment by Mcat12** [comment]
#15 adds some lines between the original's 1 & 6, so technically you are safe. I think git is smart enough to handle that. :smile:

**Comment by jacobsalmela** [comment]
I guess we'll find out!

**Comment by PromoFaux** [comment]
image

**Comment by Horkyze** [comment]
Also, do you think that ` | head -n 100` is a good choice? Perhaps it could be omitted. (but than the table can get really big...)

**Comment by jacobsalmela** [comment]
Bummer, looks like some conflicts will need to be resolved.

Also, seconding @Horkyze's comment, maybe it should be a `head -n 20`?  Or have a pulldown menu for different ranges.

**Comment by dschaper** [comment]
@Horkyze Do you want to rebase off of the updated devel branch, or would you like me to try and see if I can process the merge conflicts?

**Comment by Horkyze** [comment]
Ok, I hope I managed to resolve it. Still struggling with the command line sometimes :)

**Comment by PromoFaux** [comment]
Looks good. I wonder if we could add that PHP script you've added to the API. #notetoself.. look into this later

**Comment by Mcat12** [comment]
I'm working on merging this into devel right now.

**Comment by Horkyze** [comment]
@PromoFaux Sure we can, I can do it myself. Got a bunch of time now.

Also as @jacobsalmela noted a pulldown menu for choosing how many rows you want would be good. Therefore there is a need for new script that would return `n` rows. At it can easily be integrated into the API.

@Mcat12 should future pull requests be done into `devel`?

**Comment by PromoFaux** [comment]
It might be worth creating a new script called `api.sh`, then, and keep `choronometer.sh` seperate, with a rework to call `api.sh` to get it's details.

Then we can have api.php accept a bunch of different parameters, which it would pass to the script, which would in turn output something different depending on the parameter.

**Comment by Horkyze** [comment]
And all the hard work with processing the log would be done in `api.sh`? Which would be in the pihole repo I guess? (Mixing .php with .sh seems like bad idea)

If so, then creating new feature would require modifying 2 files in 2 repos. :(

**Comment by PromoFaux** [comment]
Yeah. That's what I did when I modified the existing `api.php`.

Where it used to do the logic itself and then output a JSON string, it now calls `chronometer.sh -j` which returns does the work and returns the same JSON string.

The idea behind my reasoning for moving it out to a shell script was to cut down on 
a) code duplication
b) inconsistencies between what was shown on `chronometer.sh` and the dashboard.

I found it far easier to parse JSON with PHP than bash...

**Comment by Mcat12** [comment]
It's merged.
Yes, future PRs should go into devel. That reminds me, we need to add that to the readme.

**Comment by Horkyze** [comment]
I understand your reasoning. So now we have 2 options:

1) Keeping two separate files for providing stats. One for the LCD and one for the web interface. 
- BAD code duplication, inconsistency (like you mentioned)
+ GOOD easy adding for new features

2) Keep all stats calculations in one file (php or sh ??) 

Whats more I think that the web interface will be the main source of stats, since it can display much more info than the small LCD. If we will lean towards option 2, I suggest adding new features into `api.php` which will be used in `index.php` (your changes can stay, it's unlikely that there will be different alg. to calculate those numbers)  and possibly in `chronometer.sh` when there will be a need to display some new stats to the LCD. 

And I also prefer PHP for JSON manipulation.

**Comment by PromoFaux** [comment]
> Keeping two separate files for providing stats. One for the LCD and one for the web interface.

Regarding that, I was thinking more along the lines of:
* `chronometer.sh` goes back to it's original purpose or only providing an LCD output
* `api.sh` provides `chronometer.sh` with the stats it needs to display. 
* `api.sh provides `api.php` with different JSON outputs, depending on parameters passed to it.

That said, might aswell just keep `api.php` and `chronometer.sh` as they are and just add on more options/parameters. 

For example running `chronometer.sh -fq` would return a JSON string with the information you need for your frequent queries table. I like this idea.

**Comment by Mcat12** [comment]
That sounds good to me.

**Comment by PromoFaux** [comment]
The only downside now to splitting `chronometer.sh -j` from `chronometer.sh` and into `api.sh` is that I'm now going to have to learn how to parse JSON in a bash script!

**Comment by dschaper** [comment]
@PromoFaux keep notes mate!

**Pull request closed without merging**
