### PR TITLE
Added a basic API to get stats via JSON

### PR DESCRIPTION
**Pull request by bricej13**

### CODE REVIEW

**Comment by jacobsalmela** [comment]
It looks pretty awesome.  So how would you get the information from a script?

**Comment by bricej13** [comment]
From an external script? It should be pretty straightforward. Here's how you'd do it from a PHP script:

```PHP
# PHP
$json = file_get_contents('http://your.piholeurl.com/admin/api.php');
$obj = json_decode($json);
```

From command line:

```Bash
# bash
wget http://your.piholeurl.com/admin/api.php
```

**Comment by jacobsalmela** [comment]
Nice.  Thanks!

**Comment by Sovex66** [comment]
Before you put à API can we have more stats ? 
Like total ad blocked, table with ad blocked by ip

I really wanna help on the Web page but I'm un able to work with Unix commande like cat awk and WC-l

Maybe serialize data and put them in database for deep chart

**Comment by jacobsalmela** [comment]
I already have enhanced stats committed locally.  It works pretty well, but I just haven't pushed them yet.  I'm pretty slow since I am a free-time developer unless I [make enough money someday](http://pi-hole.net/donate/) to do it full time.
advanced-pihole-stats-mobile

**Comment by Sovex66** [comment]
Pretty sick I like it! 

I'm a young dev and it's very interesting, this could help me to learn and use the data but I'm unable to sort the logs, did you got some good wiki ou anything helped you to do that?

**Comment by Sovex66** [comment]
Like every 24h we could setup a cronjob to delete or compress the logs and store the result in a simple file or database!

**Comment by jacobsalmela** [comment]
Yup, there is a `cron` job to do that.  The historical stats are stored in a `mysql` database.

[This FAQ](http://pi-hole.net/faq/how-do-i-read-and-interpret-the-log-file/) will probably be your best resource for the time being.

**Pull request merged**
