### PR TITLE
Added advanced whitelist/blacklist site

### PR DESCRIPTION
**Pull request by Mcat12**
This adds a few buttons,"Whitelist" and "Blacklist", which link to the editor for the lists. There is also a home button, since now the site uses more than one page. I renamed the old whitelist button to "Old Whitelist". Currently, it needs root access for gravity.sh and whitelist.sh in order to modify the lists and reload the DNS service.

Screenshot

### CODE REVIEW

**Comment by jacobsalmela** [comment]
This is pretty amazing.  I made `whitelist.txt` and `whitelist.sh` owned by `www-data`.  

I know it might be some more work, but is there any way to format your pages to fit into the same layout (the top and sidebar)?  I'm thinking of abandoning my sidebar whitelister, unless we can somehow get your inpage refresh to work like that.

Maybe your blacklist and whitelist links could be added to the sidebar.

**Comment by Mcat12** [comment]
Seeing as how adminlte runs off of bootstrap, I think it's doable. I may even be able to move the code up into the main directory, if I'm able to hook into the bootstrap and jquery used by adminlte. Also, does anything change since you

**Comment by Mcat12** [comment]
I'm thinking that the top and side bars should be added to a separate php file, then "required" so that:
1. We can focus more on what is special on the page.
2. Less duplicated code.
The syntax is: 

    <?php
    require "topbar.php";
    require "sidebar.php";
    ?>

**Comment by Mcat12** [comment]
Is jQuery being loaded twice?
https://github.com/jacobsalmela/AdminLTE/blob/whitelist/index.php#L22
and
https://github.com/jacobsalmela/AdminLTE/blob/whitelist/index.php#L242

**Comment by Mcat12** [comment]
The first one is unneeded. I removed it in the next commit.

**Comment by Mcat12** [comment]
Ok, it's almost done. I was able to almost just copy my code over. :D Also, the favicon was not working in my page and yours (I added a home button). I made the image in the img folder the favicon. Did you have a favicon before, or was that just my browser being weird?
Screenshot

**Comment by Mcat12** [comment]
Also getting rid of tee. I should have used echo instead. :D

**Comment by Mcat12** [comment]
Changes are up.

**Comment by jacobsalmela** [comment]
It looks beautiful!  I'll test it out a bit before merging.  I'll probably have to update the installer script to `chown` the script so it can actually modify the whitelist.

**Comment by Mcat12** [comment]
I'm not completely versed in Linux user privileges; will chown allow it to execute the script as root without needing to write sudo before it? Also, which script?

**Comment by jacobsalmela** [comment]
Yeah, `chown` is basically saying this user owns this file, so the Web server user `www-data` needs to be able to modify those files.  [This is the script](https://github.com/jacobsalmela/pi-hole/blob/master/automated%20install/basic-install.sh) I will modify so everything works.

**Comment by Mcat12** [comment]
Ok. By the way, how's it performing in your testing?

**Comment by jacobsalmela** [comment]
The first one was great; I'm about to install your latest changes and try everything out but it is looking very promising.

**Comment by Mcat12** [comment]
Thanks.

**Comment by Mcat12** [comment]
With the whitelist script owned by www-data, will it be able to use kill to reload the DNS server?

**Comment by Mcat12** [comment]
I'm back up and running with the new installation, but as it is 11:45pm, I have decided in favor of sleep. :sleepy:

**Comment by jacobsalmela** [comment]
Nothing wrong with sleep!

**Comment by Mcat12** [comment]
Do you want me to also take out the old whitelist?

**Comment by jacobsalmela** [comment]
Yeah, yours is much better.

**Comment by Mcat12** [comment]
Try this out. I updated to the new scripts and removed the old whitelister. Remember to give www-data sudo through visudo to whitelist.sh and blacklist.sh!

**Comment by Mcat12** [comment]
Ugh, somehow the returns replaced the die calls again...

**Comment by Mcat12** [comment]
And also changing line endings... :D Forgot about that.

**Comment by Mcat12** [comment]
This is ready to be merged.

**Comment by jacobsalmela** [comment]
Now for this one I needed to make some permission changes, yes? 

- `/etc/pihole/gravity.list`
- `/etc/pihole/whitelist.txt`
- `whitelist.sh`
- `blacklist.sh`

**Comment by jacobsalmela** [comment]
So I was able to white/blacklist without changing the permissions.  Can anyone else verify that?

**Comment by jacobsalmela** [comment]
Amazing interface BTW!

**Comment by Mcat12** [comment]
The thing that needs permissions is restarting the DNS.

**Comment by jacobsalmela** [comment]
Ahh yes.  OK.  I wonder if we can just use a separate script for that...

**Comment by Mcat12** [comment]
If it's run under www-data, it still needs sudo. The only way I can think of to get around this is using some script to check for changes to the lists and run the other scripts if anything changes.

**Comment by Mcat12** [comment]
The easiest way is to give www-data sudo access on whitelist.sh and blacklist.sh.

**Comment by Mcat12** [comment]
I think this would work. The script would definitely need to be called with sudo, since it's editing the sudoers file.
```bash
echo 'www-data    ALL=(ALL) NOPASSWD: /usr/local/bin/whitelist.sh' >> /etc/sudoers
echo 'www-data    ALL=(ALL) NOPASSWD: /usr/local/bin/blacklist.sh' >> /etc/sudoers
```

**Pull request merged**
