### PR TITLE
Changed $domains_being_blocked to point to gravity.list, instead of a…

### PR DESCRIPTION
**Pull request by PromoFaux**
Fix for #11 

See:
https://github.com/jacobsalmela/pi-hole/issues/191#issuecomment-172497941

### CODE REVIEW

**Comment by PromoFaux** [comment]
Tested the latter 2 commits locally and it works. Takes into account issue #8 

Makes sense to run on gravity.list as the white and blacklisted domains are not added/removed until this point.

**Comment by Mcat12** [comment]
Does this take into account whether or not the user is using ipv6? If they aren't, it will show them as blocking half as many as they actually are.

**Comment by PromoFaux** [comment]
Very good point. No, it was just a simple line change... perhaps <code>pihole.2.eventHorizon.txt</code> is the best place to be.. one moment please

**Comment by PromoFaux** [comment]
You know what, scratch this. I think it's probably better to put the count in a seperate file that is worked out after the gravity.list is generated, so that we can take into account white and blacklisted domains.

Ignore everything!

**Comment by PromoFaux** [comment]
This will work as a stopgap until I or someone else codes what I wrote in the above comment!

**Comment by PromoFaux** [comment]
[no longer needed] (https://github.com/jacobsalmela/AdminLTE/pull/15)

**Pull request closed without merging**
