### PR TITLE
Pending chronometer.sh changes

### PR DESCRIPTION
**Pull request by PromoFaux**
<code>index.php</code> and <code>api.php</code> changed to consume the changes made to chronometer.sh in [this pull](https://github.com/jacobsalmela/pi-hole/pull/193).

### CODE REVIEW

**Comment by Mcat12** [comment]
That link is broken

**Comment by PromoFaux** [comment]
>That link is broken
Which one?

**Comment by Mcat12** [comment]
In the first comment (index.php and api.php changed to consume the changes made to chronometer.sh in this pull.)

**Comment by PromoFaux** [comment]
image 

Yeah, I guess you can't use markdown in commits.

**Comment by Mcat12** [comment]
Well, that too

**Comment by dschaper** [comment]
When you set up your PR's I think you can set the origin to be a new branch instead of master, that would make it a little easier to test the code and prevent breakage. Merging to master is kind of a done deal. (Reverts are a pain in the posterior, lol.)

**Comment by PromoFaux** [comment]
I couldn't see the option to do so.. I'll gladly do another if that is the case...

**Comment by Mcat12** [comment]
Before you start working, you can create a new branch and change to it. Then any work you do will be put on that branch. When you're done, make a pull request to add a branch here. (I think that's how it works).

**Comment by dschaper** [comment]
capture

Just type a new branch name in the box.

**Comment by PromoFaux** [comment]
Yeah, did that, but it didn't give me an option to create a new one in the base fork.

**Comment by dschaper** [comment]
Hmm... Let me do some research.

**Comment by dschaper** [comment]
Can you grab a screenie of what you see when you do a PR?

**Comment by PromoFaux** [comment]
image

**Comment by dschaper** [comment]
Can you click on the `base TEST NEW BRANCH` dropdown and see if you get a box that you can type in?

**Comment by PromoFaux** [comment]
Yeah, I typed in "TEST NEW BRANCH" to the base branch box, and then 
image

when you then click on the branch in the drop down it redirects you to the page shown in my first screenshoy.

**Comment by dschaper** [comment]
Okay, you should then just be able to do the PR and a new branch will be created if the PR is accepted.

**Comment by dschaper** [comment]
Is the box blank because you're trying to submit a PR with no changes? Try doing that with a PR that has some changes to merge and check if the box goes green?

**Comment by PromoFaux** [comment]
Nope, the Create Pull request button is greyed out.

image

If you check [my test fork](https://github.com/PromoFaux/AdminLTE/tree/TEST-NEW-BRANCH) you'll see I made changes to the readme

**Comment by jacobsalmela** [comment]
So this PR is for a new branch called "PendingChronometerChanges"?  If I merge it, it should create the new branch?  Is that what you are saying?

**Comment by PromoFaux** [comment]
The PR is to merge my branch "PendingChronometerChanges" into the main "master"

**Comment by jacobsalmela** [comment]
Oh yes, I see now.  I read it wrong.

**Comment by PromoFaux** [comment]
Yeah, there is some confusion with the branching. As far as I can see, there is no way to duplicate a branch to the upstream without the owner creating said branch.

**Comment by dschaper** [comment]
I'll have to do some more research to see how a PR can be requested for a branch to be created on the base repo. That way we aren't merging testing code to master and instead to a new branch on origin.

**Comment by PromoFaux** [comment]
I'm pretty sure you're supposed to merge locally and test before merging on github.

[this goes over that](https://help.github.com/articles/merging-a-pull-request/#checking-out-a-pull-request-locally)

**Comment by Mcat12** [comment]
I think the idea is that the owner creates a few branches (master, v1, v1-dev) and forks can go off on their own (branching off of v1-dev to make a new feature in new branch feature). After creating the feature, they make a pull request (pr from fork's feature into origin's v1-dev). Their changes get put into the inherently unstable branch, which every once in a while gets it's features merged into v1.

**Comment by PromoFaux** [comment]
@Mcat12 has it right.

**Comment by dschaper** [comment]
@Mcat12 I think that's probably the good workflow. @jacobsalmela could create a `Devel` branch for developmental work. I'm learning new stuff too! ;)

**Comment by jacobsalmela** [comment]
Agreed.  

I wasn't expecting so much support for the project so I really need to learn more `git` stuff.  I'll make a branch now.

**Comment by dschaper** [comment]
It's the Git to GitHub integration that I'm trying to figure out. Local git repositories are a breeze for me, but when you add in GitHub as an upstream remote things get cloudy for me...

**Comment by PromoFaux** [comment]
We quite often have arguments about it at work, though we use [SVN](https://subversion.apache.org/) there, which is slightly different. One day I'll convince them to switch to git. I much prefer it.

**Comment by jacobsalmela** [comment]
@PromoFaux, I'm just trying to catch up on the activity from today.  Does this PR also fix [Pi-hole #191](https://github.com/jacobsalmela/pi-hole/issues/191#issuecomment-172497941)?

**Comment by Mcat12** [comment]
https://guides.github.com/introduction/flow/

**Comment by Mcat12** [comment]
:smile: Good thing I got to git from Github (Except then again, I sometimes have the opposite problem...). I would create a branch called dev or something.

**Comment by PromoFaux** [comment]
@jacobsalmela It fixes the issues I could see with #191, but I was not able to replicate the original issue.

**Comment by Mcat12** [comment]
That issue is with the original adminlte. The correct issue is on another repo, so you need to directly link to it.

**Comment by PromoFaux** [comment]
@Mcat12 spotted that and fixed it with a sneaky ninja-edit!

**Comment by Mcat12** [comment]
As an aside, it's kind of annoying that adminlte has such a huge branch and fork list. Github won't let me see the branch network from Graphs -> Network.

**Comment by PromoFaux** [comment]
Provided everyone else is happy with it, it's safe to merge to master @jacobsalmela

**Comment by jacobsalmela** [comment]
Everything looks good.  `chronometer.sh` seems to be working well for me.  I'll probably merge it tonight if no one spots any issues.

**Pull request merged**
